#+title: orbital-mechanics-intro -- Teodor notes

* 2023-05-05
** intro: la oss lære sammen
learning mindset, hard stuff.
Courage to face what we don't know.
David and goliath.

Asking for help.

1. Hvem kan analytisk Lagrange-mekanikk?
2. Hvem kan Clojure?
3. Hvem er ikke programmerere engang?

Jeg ønsker at vi hjelper hverandre!

Teodor selv-evaluering:

| tema              | selvrapportert kompetanse |
|-------------------+---------------------------|
| clojure           | 3/5                       |
| lagrange-mekanikk | 2/5                       |
| Newton-mekanikk   | 5/5                       |
| Astrodynamikk     | 2/5                       |

"på hvilken skala?"
På den skalaen som gir mening for meg når jeg skal vurdere hva jeg ønsker å lære.

Sitere Sam, "jeg ønsker at folk skal kunne lære disse greiene!"

Teodor mening: Emmy og Clerk er så /sykt bra greier/ at det burde vært obligatorsk pensum for de som studerer på Konstruksjonsteknikk på NTNU.
** what
CLerk, clojure, Emmy
Visualizations of planetary object movement
Sam's clerk viewer repo
** who
clojure-norway meetup
cjohnasen
Sindre, Oddmund, Julian, Neno, Ole Jacob, Eilef, Finn
** limits of my knowledge
clojure -> cjohnasen
planetary dynamics -> finn (RK4), Sam Ritchie (lagrangian mechanics)
** utkast til agenda
16-17: introduksjon til Clojure med Clerk.
Målgruppe: noen som er helt ferske i Clojure.

17-18: Simulating orbital mechanics with two bodies using Newtonian Mechanics.
Orbit visualization with [mentat-collective/Clerk-Utils]

Why isn't this good enough?
Because we don't have energy conservation.
Because we naively step forward when "integrating" force equilibrium into movement, we create or destroy energy.
We can avoid this with RK4 (ask finn to explain)

18-19 Introduction to Lagrangian mechanics -- energy stability.

1. Energy potential -- kinetic and "the other one"
2. Differentiation with respect to something
3. equations of motion. Analytical solution possible?

Ideally: ask Sam Ritchie to review, and possibly show up.
